use_frameworks!

platform :ios, '13.0'

target 'YstenVideoJackLib_Example' do
  pod 'YstenVideoJackLib', :path => '../'

  
  
  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # For simulator builds
        config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = 'arm64'
        config.build_settings['ONLY_ACTIVE_ARCH'] = 'YES'
      end
    end
  end
  
  
  pre_install do |installer|
    # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
    Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  end

#  pod 'YstenVideoJackLib','0.1.0'
  target 'YstenVideoJackLib_Tests' do
    inherit! :search_paths
  end
end



