use_frameworks!

platform :ios, '13.0'

target 'YstenVideoJackLib_Example' do
  pod 'YstenVideoJackLib', :path => '../'

  target 'YstenVideoJackLib_Tests' do
    inherit! :search_paths

    
  end
end
